name: Release build

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Setup goimports
        run: go install golang.org/x/tools/cmd/goimports@v0.17.0
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            atomgen
