name: Release build

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: make crossplatform
      - name: Preparing PKGBUILD
        run: sed -i "s/pkgver=0.0.0/pkgver=$(git tag -l | tail --lines=1)/" PKGBUILD
      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          aur: true
          updpkgsums: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            atomgen_linux_amd64
            atomgen_linux_arm
            atomgen_windows_amd64.exe
      - name: List files
        run: ls -al
